In [13]:
import numpy as np


[1 2 3 4 5 6]


In [23]:
#Task1 

array= np.arange(10)

print (array)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
# Task 2

boolen = np.ones(9)

sorted = boolen.reshape(3,3)

print (sorted)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [44]:
# Task 3 

odd = np.arange(0,10, 2)

print(odd)

[0 2 4 6 8]


In [46]:
# Task 4

odd = np.arange(0,10, 2)

print(odd)

[0 2 4 6 8]


In [61]:
# Task 4


odds = np.arange(10)

odds[1 ] = -1
odds[3 ] = -1
odds[5] = -1
odds[7] = -1
odds[9 ] = -1

odds

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [68]:
#Task 5 

a = np.arange(1,7)

a2 = a.reshape(3,2)

a2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [91]:
#Task 6

a= np.arange(1,10)

b= np.arange(11,20)

c = np.vstack((a,b))

# The sum off all 

sum = np.sum(c)

# sum of all using npdot

sum2 = np.dot(a,b)

sum2


735